wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/acyrthosiphon_pisum/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/adineta_vaga/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/aedes_aegypti/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/amphimedon_queenslandica/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/anopheles_darlingi/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/anopheles_gambiae/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/anoplophora_glabripennis/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/apis_mellifera/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/atta_cephalotes/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/belgica_antarctica/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/bombus_impatiens/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/bombus_terrestris/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/bombyx_mori/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/brugia_malayi/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_brenneri/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_briggsae/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_elegans/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_japonica/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_remanei/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/capitella_teleta/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/crassostrea_gigas/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/culex_quinquefasciatus/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/danaus_plexippus/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/daphnia_pulex/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/dendroctonus_ponderosae/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_ananassae/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_erecta/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_grimshawi/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_melanogaster/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_mojavensis/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_persimilis/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_pseudoobscura/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_sechellia/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_simulans/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_virilis/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_willistoni/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_yakuba/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/heliconius_melpomene/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/helobdella_robusta/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/ixodes_scapularis/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/lepeophtheirus_salmonis/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/lingula_anatina/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/loa_loa/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/lottia_gigantea/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/lucilia_cuprina/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/mayetiola_destructor/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/megaselia_scalaris/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/melitaea_cinxia/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/mnemiopsis_leidyi/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/nasonia_vitripennis/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/nematostella_vectensis/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/octopus_bimaculoides/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/onchocerca_volvulus/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/pediculus_humanus/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/pristionchus_pacificus/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/rhodnius_prolixus/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/sarcoptes_scabiei/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/schistosoma_mansoni/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/solenopsis_invicta/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/stegodyphus_mimosarum/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/strigamia_maritima/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/strongylocentrotus_purpuratus/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/strongyloides_ratti/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/tetranychus_urticae/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/thelohanellus_kitauei/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/tribolium_castaneum/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/trichinella_spiralis/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/trichoplax_adhaerens/pep/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/zootermopsis_nevadensis/pep/*.fa.gz  
