wget ftp://ftp.ensembl.org/pub/current_fasta/ailuropoda_melanoleuca/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/anas_platyrhynchos/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ancestral_alleles/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/anolis_carolinensis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/aotus_nancymaae/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/astyanax_mexicanus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/callithrix_jacchus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/capra_hircus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/carlito_syrichta/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cavia_aperea/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cebus_capucinus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cercocebus_atys/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/chinchilla_lanigera/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/chlorocebus_sabaeus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/choloepus_hoffmanni/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/colobus_angolensis_palliatus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cricetulus_griseus_chok1gshd/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cricetulus_griseus_crigri/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/dipodomys_ordii/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/equus_caballus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/felis_catus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ficedula_albicollis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/fukomys_damarensis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/gadus_morhua/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/gorilla_gorilla/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/heterocephalus_glaber_female/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/heterocephalus_glaber_male/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ictidomys_tridecemlineatus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/jaculus_jaculus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/latimeria_chalumnae/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/lepisosteus_oculatus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/macaca_fascicularis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/macaca_nemestrina/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mandrillus_leucophaeus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/meleagris_gallopavo/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mesocricetus_auratus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/microcebus_murinus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/microtus_ochrogaster/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_caroli/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_129s1svimj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_aj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_akrj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_balbcj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_c3hhej/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_c57bl6nj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_casteij/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_cbaj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_dba2j/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_fvbnj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_lpj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_nodshiltj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_nzohlltj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_pwkphj/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_wsbeij/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_pahari/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_spretus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mustela_putorius_furo/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/nannospalax_galili/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/nomascus_leucogenys/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/notamacropus_eugenii/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ochotona_princeps/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/octodon_degus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/oreochromis_niloticus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ovis_aries/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pan_paniscus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/papio_anubis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pelodiscus_sinensis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/peromyscus_maniculatus_bairdii/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/petromyzon_marinus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/poecilia_formosa/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pongo_abelii/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/procavia_capensis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/propithecus_coquereli/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pteropus_vampyrus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/rhinopithecus_bieti/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/rhinopithecus_roxellana/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/saimiri_boliviensis_boliviensis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/sarcophilus_harrisii/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/sus_scrofa/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/taeniopygia_guttata/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/tursiops_truncatus/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/vicugna_pacos/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis/pep/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/xiphophorus_maculatus/pep/*.fa.gz  
