wget ftp://ftp.ensembl.org/pub/current_fasta/ailuropoda_melanoleuca/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/anas_platyrhynchos/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ancestral_alleles/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/anolis_carolinensis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/aotus_nancymaae/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/astyanax_mexicanus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/bos_taurus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/caenorhabditis_elegans/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/callithrix_jacchus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/canis_familiaris/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/capra_hircus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/carlito_syrichta/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cavia_aperea/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cavia_porcellus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cebus_capucinus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cercocebus_atys/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/chinchilla_lanigera/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/chlorocebus_sabaeus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/choloepus_hoffmanni/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ciona_intestinalis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ciona_savignyi/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/colobus_angolensis_palliatus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cricetulus_griseus_chok1gshd/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/cricetulus_griseus_crigri/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/danio_rerio/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/dasypus_novemcinctus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/dipodomys_ordii/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/echinops_telfairi/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/equus_caballus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/erinaceus_europaeus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/felis_catus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ficedula_albicollis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/fukomys_damarensis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/gadus_morhua/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/gallus_gallus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/gasterosteus_aculeatus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/gorilla_gorilla/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/heterocephalus_glaber_female/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/heterocephalus_glaber_male/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/homo_sapiens/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ictidomys_tridecemlineatus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/jaculus_jaculus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/latimeria_chalumnae/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/lepisosteus_oculatus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/loxodonta_africana/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/macaca_fascicularis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/macaca_mulatta/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/macaca_nemestrina/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mandrillus_leucophaeus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/meleagris_gallopavo/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mesocricetus_auratus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/microcebus_murinus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/microtus_ochrogaster/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/monodelphis_domestica/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_caroli/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_129s1svimj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_aj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_akrj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_balbcj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_c3hhej/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_c57bl6nj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_casteij/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_cbaj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_dba2j/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_fvbnj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_lpj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_nodshiltj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_nzohlltj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_pwkphj/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_musculus_wsbeij/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_pahari/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mus_spretus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/mustela_putorius_furo/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/myotis_lucifugus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/nannospalax_galili/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/nomascus_leucogenys/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/notamacropus_eugenii/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ochotona_princeps/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/octodon_degus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/oreochromis_niloticus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ornithorhynchus_anatinus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/oryctolagus_cuniculus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/oryzias_latipes/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/otolemur_garnettii/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/ovis_aries/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pan_paniscus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pan_troglodytes/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/papio_anubis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pelodiscus_sinensis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/peromyscus_maniculatus_bairdii/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/petromyzon_marinus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/poecilia_formosa/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pongo_abelii/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/procavia_capensis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/propithecus_coquereli/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/pteropus_vampyrus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/rattus_norvegicus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/rhinopithecus_bieti/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/rhinopithecus_roxellana/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/saccharomyces_cerevisiae/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/saimiri_boliviensis_boliviensis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/sarcophilus_harrisii/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/sorex_araneus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/sus_scrofa/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/taeniopygia_guttata/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/takifugu_rubripes/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/tetraodon_nigroviridis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/tupaia_belangeri/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/tursiops_truncatus/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/vicugna_pacos/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/xenopus_tropicalis/cds/*.fa.gz  
wget ftp://ftp.ensembl.org/pub/current_fasta/xiphophorus_maculatus/cds/*.fa.gz  
