wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/acyrthosiphon_pisum/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/adineta_vaga/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/aedes_aegypti/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/amphimedon_queenslandica/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/anopheles_darlingi/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/anopheles_gambiae/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/anoplophora_glabripennis/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/apis_mellifera/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/atta_cephalotes/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/belgica_antarctica/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/bombus_impatiens/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/bombus_terrestris/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/bombyx_mori/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/brugia_malayi/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_brenneri/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_briggsae/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_elegans/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_japonica/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/caenorhabditis_remanei/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/capitella_teleta/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/crassostrea_gigas/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/culex_quinquefasciatus/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/danaus_plexippus/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/daphnia_pulex/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/dendroctonus_ponderosae/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_ananassae/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_erecta/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_grimshawi/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_melanogaster/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_mojavensis/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_persimilis/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_pseudoobscura/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_sechellia/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_simulans/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_virilis/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_willistoni/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_yakuba/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/heliconius_melpomene/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/helobdella_robusta/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/ixodes_scapularis/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/lepeophtheirus_salmonis/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/lingula_anatina/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/loa_loa/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/lottia_gigantea/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/lucilia_cuprina/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/mayetiola_destructor/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/megaselia_scalaris/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/melitaea_cinxia/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/mnemiopsis_leidyi/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/nasonia_vitripennis/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/nematostella_vectensis/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/octopus_bimaculoides/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/onchocerca_volvulus/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/pediculus_humanus/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/pristionchus_pacificus/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/rhodnius_prolixus/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/sarcoptes_scabiei/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/schistosoma_mansoni/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/solenopsis_invicta/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/stegodyphus_mimosarum/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/strigamia_maritima/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/strongylocentrotus_purpuratus/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/strongyloides_ratti/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/tetranychus_urticae/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/thelohanellus_kitauei/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/tribolium_castaneum/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/trichinella_spiralis/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/trichoplax_adhaerens/cds/*.fa.gz  
wget ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/zootermopsis_nevadensis/cds/*.fa.gz  
